global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'phpfpm'
  metrics_path: /metrics
  static_configs:
    - targets: ['phpfpm-exporter:9253']
- job_name: 'nginx'
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['nginx-exporter:9113']

